### ISSUE TITLE
It doesn't run... may be you forgot to include the modules?

### ISSUE THREAD

**Issue by ilumnisaint** [ManuSquall/QIUM-project#2]
when i run node  app.js:

$ node app.js
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- F:\playgroundGIT\QIUM-project\app.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:840:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1019:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:77:18)?[39m
    at Object.<anonymous> (F:\playgroundGIT\QIUM-project\app.js:2:17)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1133:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:977:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'F:\\playgroundGIT\\QIUM-project\\app.js'?[39m ]
}

**Comment by ManuSquall** [comment]
Sorry for the late @ilumnisaint , have you installed Express? If not run:
"npm install express" command in folder directory.

Please refer here: https://stackoverflow.com/questions/14949118/node-js-error-cannot-find-module-express

**Comment by ManuSquall** [comment]
And you have to run "npm install" before run the app, i didn't include node modules because of the size
